---
title: "Electric power sector transition scenarios"
author: '@ideea'
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Configuration
```{r, eval = T}
nreg <- 5 # number of regions
offshore <- FALSE # TRUE/FALSE
islands <- FALSE
# time resolution
base_year <- 2020
# ndays_sample <- 12 # 1 day per month, 12 months
# ndays_sample <- 36 # 3 days per month, 12 months
# ndays_sample <- 60 # 5 days per month, 12 months
# ndays_sample <- 84 # 7 days per month, 12 months
ndays_sample <- 365 # full year

```

```{r, eval=TRUE, include=FALSE, message=FALSE, warning=FALSE}
```

```{r setup, message=FALSE, warning=FALSE}
library(IDEEA)
library(tidyverse)
library(data.table)
library(sf)
library(glue)
# remotes::install_github("energyRt/timeslices")

regN <- glue("reg", nreg)
regN_off <- paste0(regN, "_off")

```

## Regions

```{r regions}
ideea_sf <- get_ideea_map(nreg, offshore = T, reg_off = T)
plot(ideea_sf[regN], key.width = lcm(4))

```

## Electricity model
```{r}
# Import electricity model objects
elc <- ideea_modules$electricity[[regN]]
names(elc)
# summary(elc)

# A model with the default configuration
mod <- newModel(
  name = glue("IDEEA_ELC_{regN}"),
  desc = "IDEEA electricity example model",
  region = unique(ideea_sf[[regN]]),
  discount = 0.05,
  calendar = ideea_modules$calendars$calendar_d365_h24_full,
  horizon = ideea_modules$calendars$horizon_2020_2060_by_10,
  data = newRepository(
    name = glue("repo_electricity_{regN}"),
    elc$repo_comm,
    # supply & import
    elc$repo_supply,
    elc$repo_geoccs,
    # Generating technologies
    elc$ECOA, # coal-fired generators
    elc$EGAS, # gas-fired generators
    elc$ENUC, # nuclear generators
    elc$EHYD, # hydro generators
    elc$ESOL, # solar generators
    elc$EWIN, # wind generators
    elc$EWIF, # wind generators
    elc$EBIO, # biomass generators
    elc$repo_ccstechs,
    # capacity (weather) factors
    elc$WSOL, # solar capacity factor
    elc$WWIN, # wind capacity 
    elc$WWIF, # wind capacity 
    elc$WHYD, # hydro capacity factor
    # battery
    elc$STG_BTR, # battery storage with yearly cycle
    # STG_BTR_daily = STG_BTR_daily, # battery storage with daily cycle
    # transmission
    elc$repo_transmission_ac, # transmission network
    elc$repo_transmission_dc, # transmission network   
    # demand
    elc$DEMELC_BY, # electricity demand in the base year
    elc$DEMELC_2X # electricity demand growth
  )
)


```

## Scenarios

```{r}
set_progress_bar(type = "cli")
# reference scenario with subset time resolution
scen_REF_sub <- interpolate_model(
  mod,
  name = "REF_sub", # indicating 'subset'
  calendar = ideea_modules$calendars$calendar_d365_h24_subset_1day_per_month,
  horizon = ideea_modules$calendars$horizon_2050
)

scen_REF_sub@path <- file.path(
  ideea_scenarios(),
  ideea_scenario_dir_name(
    name = "REF_sub", 
    model_name = scen_REF_sub@model@name, 
    calendar_name = scen_REF_sub@settings@calendar@name, 
    horizon_name = "2050"
    )
  )

scen_REF_sub <- write_sc(
  scen_REF_sub,
  # solver = solver_options$gams_gdx_cplex_barrier
  # solver = solver_options$gams_gdx_cplex_parallel
  solver = solver_options$julia_highs_barrier
  # solver = solver_options$julia_highs_simplex
  # solver = solver_options$julia_highs_parallel
)
scen_REF_sub@status
scen_REF_sub@misc$tmp.dir

scen_REF_sub <- solve_scenario(scen_REF_sub, wait = F)
scen_REF_sub <- read(scen_REF_sub)
summary(scen_REF_sub)

```

... process results
